# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feature-branch-name

pool:
  vmImage: ubuntu-latest #windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '22.x'
- script: npm ci 
  displayName: 'Install Playwright Deps'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: npx playwright test tests/AzureDevopsPractise1.spec.ts --project='chromium'
  displayName: 'Start Execution'

